kaonasi-biwa/Twitter-UI-Customizer

- background.js
- manifest.json
- scr/style.js
ReturnTwitterInfoの内容を適用させました(manifest.jsonのみ書き換えたので申し訳ないのですが、chrome/firefoxへの適用お願いします。)
> Merged ReturnTwitterInfo

- scr/options.js
アロー関数にしてみた
セミコロンつけてみた
インデント変えてみた
> 個人的に気になったとこを変えてみた

- scr/popup.html
ポップアップ画面にCSSを適用しました。  
変更後はこちらです。
- 設定画面などへのリンクをボタン風に背景色を設定するなどした
- リンクと、メッセージ部分をdivタグで囲んで、余白はmarginで基本的に取るように調節して、brタグを一部削除した
- リンクにはホバー、アクション時のスタイルも設定することでUXが高くなった可能性もある？
- インデントの修正
<details><summary>余談</summary>
今回からneovimを使ってみていますが効率は上がるどころか落ちている感じがします。  
慣れていないのと、キーバインドの設定ミスのせいかな。  
LSP周りとhop.nvimあたりはもう少し考えるべきかもしれない。
</details>
> ポップアップ画面のデザイン変更

- TUIC/options/options.html
- TUIC/popup/popup.html
- _locales/en/messages.json
- _locales/ja/messages.json
- addI18nTags.md
- i18n/en.json
- i18n/ja.json
- scr/style.js
追加分の(雑な)英訳です
ついでにタグのtypoとEdgeで怒られたのを直しておきました
多分大丈夫なはず...多分
> バグ&typo修正と追加分の英訳

- i18n/en.json
> v2.10.1追加分の英訳

- README.md
- i18n/en.json
invisibleItems-discoverMoreの英訳の追加と既存の英訳をちょっとだけわかりやすくしただけ
> v2.11.4追加分の英訳

- i18n/en.json
> 英訳(v2.12.0追加分)

- i18n/en.json
いつもの雑な英訳 (Crowdinを使うか別repoにするとかしないとPRが無限に増えていきそう)
そういえばサイドバーのボタンの一部が機能しなくなってますね(
> 英訳(2.12.3追加分)

- README.md
- scr/applyCSS.js
- scr/index.js
- scr/library.js
- scr/runningSafemode.js
Special ThanksのCrowdinが追加された部分がしっかり見えるように修正しました。
追記：細かくて申し訳ないです
> セーフモードの修正、README.mdの修正

- .github/workflows/packaging.yml
- background.js
- manifest_chrome.json
- manifest_firefox.json
ついでにmanifestの権限設定を詰めておきました
debugとかgitignoreのversionTUIC.txtを消すかは任せます(
> 今度こそversionTUIC.txtを廃止する

- README.md
- npm-scripts/run.js
`npm run debug firefox -- --firefox="C:\Program Files\Mozilla Firefox\firefox.exe"`
これでOK
> Firefox 系ブラウザーでバイナリ指定を行えるように

- i18n/ja.json
- src/data.js
- src/observer.js
おはようございます。今日も一日リファクタリング頑張りましょう。
> 設定画面のプレミアム関連項目の非表示機能追加

- background.js
- src/applyCSS.js
- src/index.js
- src/library.js
- src/option.js
- src/runningSafemode.js
あんまり変更してないですが、
* 主にif文やTUICPref周りの`event.target.getAttribute("TUICColor")`などの多用を直す
* 不要なif文の削除
* `Element.remove()`にオプショナルチェーンを使用する
* TUICDfaultColor → TUICDefaultColorに
ミスとかあったらごめんなさい...
> if文とかnull演算子とかオプショナルチェーンとかを見直す & typoを修正

- updateI18n.mjs
This PR refactors, documents, and speed up code by at least 5 times by using async where possible!
Before:
After:
> updatel18n.mjs: refactor and speed-up

- updateI18n.mjs
ここ数分で話題に上がっている updateI18n.mjs をさらに高速化しました。
> 並列の中の直列を並列化

- .github/workflows/i18nUpdate.yml
- LICENSE
- README.md
- manifestConfigs.json
- src/content/applyCSS.js
Readmeをなんか良い感じにしたりしました。
あとi18nUpdateのコミットをするユーザーをFloorpのUA更新のやつと同じにしました。
変えたくなければmergeする前に言ってもらえれば戻します。
あとの細かい変更はあまりテストしてないけど大きな影響はない...はず
> Readmeの改善+α

- README.md
> プロフィールをプロファイルに

- src/content/data.js
こんなバグ(TUICで追加されたボタンだけ起きる)
多分直ったと思う
何度やってもChrome用にビルドできなかったのでデバッグは諦めました()
> Chromiumでサイドバーに空白ができる問題を修正

- README.md
- src/content/data.js
ReadmeにCrowdinのバッジを追加したりしました。
↓#79 のバグの原因のTwitter側の仕様変更がもとに戻ってまたバグったっぽいので戻しました
> Readmeとバグを修正

- .eslintrc.js
- src/content/data.js
- src/content/observer.js
修正しました。
なんかobserver.js#L204を変えたせいかわからないけどたまに適用されない気がする
> リンクカードを文字サイズ変更に対応

- .stylelintrc.js
- package.json
- src/content/style.css
タイトル通り
現時点で`.TUICDefaultColor`の適用箇所で同時に付くことはないので問題はないが、
`!important`が付いた`margin`と`margin-top とか`が同時に付いている場合どちらが優先されるのか不明(というか知らない)
> Stylelintの警告に対処

- .github/workflows/packaging.yml
- eslint.config.js
- npm-scripts/change-manifest.js
- package.json
- pnpm-lock.yaml
- vite.config.ts
chromeCRXのGitHubでのビルドはシークレットキーがないのでテストできていません。
ローカルでは.env.localによるrepoの変更が反映されるのを確認しております。
> Fix Github Action Build

- .github/workflows/i18nUpdate.yml
- .github/workflows/lint.yml
- .github/workflows/packaging.yml
- npm-scripts/change-manifest.js
- vite.config.ts
注: workflow_dispatchの時にTagを指定した場合でもReleaseされます
> workflowを改善

- src/content/data.ts
- src/content/library.ts
- src/content/modules/observer/functions.ts
- src/content/modules/pref/index.ts
- src/content/safemode.ts
- src/content/styles/style-tuicFeatures.css
- vite.config.ts
https://github.com/kaonasi-biwa/Twitter-UI-Customizer/commit/abee0a5c9eb3dba11f9b70b0693939be4a019739 ←よくわからないでやったけど大丈夫そう?
> リンクカードの仕様変更に対応

- package.json
- pnpm-lock.yaml
- src/shared/options/injectSafeMode.ts
vue 3.4への更新による影響はないと思う...多分
autoprefixerはpostcss用だよね...?
> chore: npmパッケージを更新

- README.md
- README_EN.md
> README: add english readme

- src/content/data.ts
- src/content/library.ts
- src/content/modules/observer/functions.ts
- src/content/observer.ts
色々Closest(及びそれ派生)に変えてみたんですけど、どちらのほうが動作・よみやすさ的に良いのか...
> Closestに変えてみた

- npm-scripts/change-manifest.js
- npm-scripts/update-i18n.js
- package.json
- vite.config.ts
> fix(build): GHAでbuildするとエラーが出るのを修正

- src/content/index.ts
- src/content/library.ts
- src/content/modules/htmlClass/classManager.ts
- src/content/modules/observer/errorDialog.ts
- src/content/modules/observer/functions/fixDM.ts
- src/content/modules/observer/functions/rightSidebarTexts.ts
- src/content/modules/observer/functions/sidebarBtn/index.ts
- src/content/modules/observer/functions/tweetSettings/index.ts
- src/content/modules/observer/functions/tweetSettings/placeEngagementsLink.ts
- src/content/modules/observer/functions/tweetSettings/showLinkCardInfo.ts
- src/content/modules/observer/functions/tweetSettings/tweetTopButtons.ts
- src/content/modules/observer/index.ts
- src/shared/options/components/RadioButton.vue
- src/shared/options/modules/importSettings.vue
Please refer to commit message ;)
> Refactoring

- src/content/modules/observer/functions/fixTwittersBugs.ts
- src/content/modules/observer/index.ts
今のところ目立った不具合はないのでマージ
ふぁみさんありがとう...！！！
> Observer高速化(ふぁみさんのコード)

- src/popup/popup.html
- src/popup/popup.pcss
- src/popup/popup.ts
設定画面のデザイン変更に合うように、ポップアップのデザインも変更しました。
Chromium系では、アプデ設定を開くとスクロールバーがちょっとかっこ悪いです（気が向いたら直すかも...）。
|上の方|下の方・アプデ設定|
|----|----|
|![tuic_newpopup](https://github.com/kaonasi-biwa/Twitter-UI-Customizer/assets/121326808/2663c023-ef1c-4299-9edf-2bbd8806b4b7)|![tuic_newpopup_upd](https://github.com/kaonasi-biwa/Twitter-UI-Customizer/assets/121326808/db690848-0043-4e1f-a438-fe1470125316)|
> ポップアップのリデザイン

- src/content/styles/style-tlui.css
- src/content/styles/style-tuicSettingPage.css
- src/options/options.pcss
- src/popup/popup.pcss
e1c72739cd1bf71bea66ffb479f68ca49af1f665 でボタンのテキストが中央寄せになるようにしました。
後は`pnpm format`をして、lintが通るようにしてみました。
> 設定画面のボタンのテキストを中央寄せに

- src/shared/settings/modules/settingTweet.vue
なんかCheckBoxのValueが違ったらしい。
ちょこちょこ投げて申し訳ないです、明日以降でいいのでマージしてください。
> エンゲージメントのリンク表示設定が機能しないのを修正

- src/content/modules/observer/functions/tweetSettings/showLinkCardInfo.ts
マージンを追加していい感じにしてみました
レスポンシブ的にも問題はないはずです...
|前|後|
|----|----|
| ![image](https://github.com/kaonasi-biwa/Twitter-UI-Customizer/assets/121326808/3b116ac9-0d7a-4b00-9eee-db776f9da305) | ![image](https://github.com/kaonasi-biwa/Twitter-UI-Customizer/assets/121326808/6828b967-0106-42d5-b9ac-752c8b209f3d) |
> LinkCardの情報欄にマージンを追加

- eslint.config.js
- package.json
- pnpm-lock.yaml
- src/content/modules/i18n/index.ts
- src/content/styles/style-tuicFeatures.css
- vite.config.ts
esp. https://github.com/vuejs/language-tools/issues/5018
#188
> Fix lint error

- manifest.config.ts
related to https://github.com/kaonasi-biwa/Twitter-UI-Customizer/issues/203#issuecomment-2856933737
Chrome/FirefoxともにOpen-Deck上での動作を確認済
> feat: iframe内のTwitterにもTUICが適用されるように

- .vscode/extensions.json
- eslint.config.js
- package.json
- pnpm-lock.yaml
- src/content/modules/observer/functions/tweetSettings/index.ts
> fix: 引用のshowMoreも展開しようとしてしまう問題を修正
